package com.uottawa.choremanager;

import java.util.ArrayList;
import java.util.Date;

/**
 * Created by Raymo on 2017-11-27.
 */


public class Task {
    private String name;
    private int startDate;
    private String description;
	private boolean done;
    private int endDate;
    private Profile owner;
    private ArrayList<SubTask> subTaskList;
    private String id;



    public Task(String name, int startDate,
                String description, int endDate,
                Profile owner){

        this.name = name;
        this.startDate = startDate;
        this.description = description;
        this.done = false;
        this.endDate = endDate;
        this.owner = owner;
        this.subTaskList = new ArrayList<SubTask>();
    }


    public void addSubTask(String subTaskName){
        SubTask newSubTask = new SubTask(subTaskName, false);
        subTaskList.add(newSubTask);
    }

    //Returns the requested SubTask or null if the SubTask does not exist
    public SubTask getSubTask(String name){
        for(SubTask s: subTaskList){
            if(name.equals(s)){ return(s); }
        }
        return(null);
    }



    //Removes the specified SubTask
    public void removeSubTask(String name){

        SubTask toBeRemoved;
        //True if the SubTask is found

        for(SubTask s: subTaskList){
            if(name.equals(s)){
                toBeRemoved = s;
                subTaskList.remove(s);
                break;
            }
        }

    }



    //The following Code was generated by UmpleOnline
    // http://cruise.eecs.uottawa.ca/umpleonline/umple.php?model=171128354777
    //Rewritten by Austin Tambakopoulos
    //------------------------
    // INTERFACE
    //------------------------
	
	public boolean getDone()
    {
        return done;
    }
	
	public boolean setDone(boolean aDone)
    {
        this.done = aDone;
        return true;
    }
	
	public boolean setId(String id){
        this.id = id;
        return true;
    }

    public boolean setName(String aName)
    {
        this.name = aName;
        return true;
    }

    public boolean setStartDate(int startDate)
    {
        this.startDate = startDate;
        return true;
    }

    public boolean setDescription(String aDescription)
    {
        this.description = aDescription;
        return true;
    }

    public boolean setEndDate(int endDate)
    {
        this.endDate = endDate;
        return true;
    }

    public boolean setOwner(Profile aOwner)
    {
        owner = aOwner;
        return true;
    }

    public String getName()
    {
        return name;
    }

    public int getEndDate()
    {
        return endDate;
    }

    public String getDescription()
    {
        return description;
    }

    public int getStartDate()
    {
        return startDate;
    }

    public Profile getOwner()
    {
        return owner;
    }

    public String getId(){
	    return id;
	}

    public String toString()
    {
        return getName();
        /*Fix to string please
        return super.toString() + "["+
                "name" + ":" + getName()+ "," +
                "description" + ":" + getDescription()+ "," +
                "reoccurRate" + ":" + getReoccurRate()+ "]" + System.getProperties().getProperty("line.separator") +
                "  " + "deadline" + "=" + (getDeadline() != null ? !getDeadline().equals(this)  ? getDeadline().toString().replaceAll("  ","    ") : "this" : "null") + System.getProperties().getProperty("line.separator") +
                "  " + "reoccurEnd" + "=" + (getReoccurEnd() != null ? !getReoccurEnd().equals(this)  ? getReoccurEnd().toString().replaceAll("  ","    ") : "this" : "null") + System.getProperties().getProperty("line.separator") +
                "  " + "owner" + "=" + (getOwner() != null ? !getOwner().equals(this)  ? getOwner().toString().replaceAll("  ","    ") : "this" : "null");*/
    }

    //End Citation
}
